### ISSUE TITLE
重命名work文件夹到readhub

### ISSUE THREAD

**Issue by gutenye** [ywyanbin/HTML-CSS#1]
后面还有好多works呢:)

**Comment by ywyanbin** [comment]
1.适应手机跟PC端的网页需要的是什么知识
2.readhub页面上每段话都有扩展（点击文字就会出现全部的内容），那个是靠什么实现的

**Comment by gutenye** [comment]
> 1.适应手机跟PC端的网页需要的是什么知识

这个叫 Responsive Web Design, 这三个资源够你学了:
- https://developers.google.com/web/fundamentals/design-and-ux/responsive/
- https://developer.mozilla.org/en-US/docs/Web/Apps/Progressive/Responsive/responsive_design_building_blocks
- https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

信息量很大，慢慢看，多花点时间, 多看几遍

> 2.readhub页面上每段话都有扩展（点击文字就会出现全部的内容），那个是靠什么实现的

这个用js+css实现. 到时候我给你演示下。

**Comment by ywyanbin** [comment]
好的，我先继续扫js的盲

**Comment by gutenye** [comment]
以后有问题新建一个Issue.
这样的话，每个issue解决了都能关闭。
