### ISSUE TITLE
设置Github Pages

### ISSUE THREAD

**Issue by gutenye** [ywyanbin/HTML-CSS#2]
Steps
1. 点击Settings
2. 找到GitHub Pages -> Source
3. 修改 gh-pages branch 为 master branch. 点击save
4. 效果如图

<img width="508" alt="screen shot 2018-10-09 at 6 56 54 pm" src="https://user-images.githubusercontent.com/377544/46664997-1be1a980-cbf5-11e8-87aa-302d79540fe6.png">

**Comment by gutenye** [comment]
@ywyanbin 这个完成了吗？

**Comment by gutenye** [comment]
把readhub.html改成index.html, 好了说下

**Comment by ywyanbin** [comment]
好了

**Comment by gutenye** [comment]
这个目的是你可以直接访问这个链接来查看你写的网页了: https://ywyanbin.github.io/HTML-CSS/readhub/
