### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by gutenye** [ywyanbin/HTML-CSS#9]
- https://try.github.io/

基本命令先学会: 下载，编辑，上传
```
$ git clone git@github.com:ywyanbin/HTML-CSS.git
$ cd HTML-CSS
$ 编辑 readhub/index.html
$ git add readhub/index.html
$ git commit -m '任意消息'
$ git push -u origin master
```

更新
```
$ git pull
```

**Comment by ywyanbin** [comment]
姐夫，我把git bush下好了，是重新走一遍吗，就是本地创建ssh key这些流程？

**Comment by ywyanbin** [comment]
http://blog.jobbole.com/102957/    姐夫我如果按照这个教程学git，弄好的那些个库还能不能还原？现在就是我不知道命令输入后运行会怎么样，所以有点犹豫。。。。
